version: "3.4"

services:
  nginx:
    restart: unless-stopped
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - web

  api:
    build:
      context: ./api
    restart: unless-stopped
    environment:
      ENVIRONMENT: development
      FLASK_ENV: development
      TABEL_CONNECTION_STRING: "DefaultEndpointsProtocol=https;AccountName=lcmdevstorage;AccountKey=o9//wbArh+VSv8wSMTVXHwAJieAuxWG2u7orRiQGIcZ6LLKQE2qW8kOnOwGeR1qU+9m1B6psTUCGspeqJuR6Kg==;EndpointSuffix=core.windows.net"
      TABEL_KEY: "o9//wbArh+VSv8wSMTVXHwAJieAuxWG2u7orRiQGIcZ6LLKQE2qW8kOnOwGeR1qU+9m1B6psTUCGspeqJuR6Kg=="
    volumes:
      - ./api/:/code
    command: ["python","/code/util/load_test_data.py"]

  web:
    build:
      context: ./web
      target: development
    restart: unless-stopped
    stdin_open: true
    volumes:
      - ./web/src:/code/src
