[tool.poetry]
name = "lcm"
version = "0.1.0"
description = "Lost Circulation Material"
authors = ["Stig Ofstad <stoo@equinor.com>", "Eirik Ola Aksnes <eaks@equinor.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
flask = "^1.1.2"
azure-cosmosdb-table = "^1.0.6"
numpy = "^1.19.1"
xlrd = "^1.2.0"
connexion = "2.7.0"
flask-cors = "3.0.9"
swagger-ui-bundle = "0.0.8"
azure-storage-blob = "^12.5.0"
PyJWT = "^1.7.1"
cachetools = "^4.1.1"
matplotlib = "^3.3.2"
tabulate = "^0.8.7"

[tool.poetry.dev-dependencies]
pytest = "^5.4"
bandit = "^1.6.2"
black = "^20.8b1"
safety = "^1.9.0"

[tool.black]
line-length = 119
target-version = ['py38']
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
)/
'''
[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

