name: CI

on:
  push:
    branches:
      - master

jobs:
  test-report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: "Create report"
        run: docker-compose build api && docker-compose run api python tests/optimizer_test.py

      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: algorithm-report
          path: api/algo_test_report.png
